version: '2'
services:
  openldap:
    image: osixia/openldap:1.2.2
    container_name: kassis-ldap
    environment:
      LDAP_ORGANISATION: "kassis"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "kassispassword"
    ports:
    - "389:389"
    command: --copy-service
    volumes:
    #- "./storage/ldapStorage:/var/lib/ldap"
    - "./openldap/config/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom"
  ldapadmin:
    image: osixia/phpldapadmin:0.7.2
    container_name: kassis-ldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
    - "3100:80"
    links:
    - "openldap:ldap"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: kassis-rabbitmq
    ports:
    - "15672:15672"
    - "5672:5672"
  postgres-data:
    image: busybox
    volumes:
      - /var/lib/postgresql/data
    container_name: postgres-datastore
  postgresql:
    image: postgres:11
    container_name: kassis-db
    ports:
      - "5432:5432"
    restart: always
    volumes_from:
      - postgres-data
    environment:
      POSTGRES_PASSWORD: postgres
  es:
    container_name: kassis-es
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    build:
      context: .
      dockerfile: ./dockerfiles/elasticsearch/Dockerfile
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    container_name: kassis-kibana
    environment:
      SERVER_NAME: localhost:5601
      ELASTICSEARCH_URL: http://kassis-es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
volumes:
  esdata1:
    driver: local
